ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8091
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5435/task_db"
  user: "task_service"
  password: "password"
pubsub:
  projectId: "local-project"
  topics:
    userRegistered: "user-registered"
    userDeleted: "user-deleted"
  subscriptions:
    userRegistered: "task-service-user-registered-sub"
    userDeleted: "task-service-user-deleted-sub"