ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8090
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5434/user_db"
  user: "user_service"
  password: "password"
pubsub:
  projectId: "local-project"
  topics:
    userDeleted: "user-deleted"